### ISSUE TITLE
Incompatible php version for Laravel 7

### ISSUE THREAD

**Issue by baceto90** [laravel-enso/cnp-validator#4]
Hello friends,
i do not think the minimum php version for this package should be 7.4.0 because Laravel 7 requires 7.2.5 and hence the incompatibility comes. This causes all users to upgrade their php version.

P.S. sorry for my english :/

**Comment by aocneanu** [comment]
Hi,

The package uses short closures so 7.4 is a minimum requirement.

**Comment by baceto90** [comment]
I know and everyone wants to use it, but that force users to upgrade php version that Laravel not required. This is not very appropriate. Thanks for the package.

**Comment by aocneanu** [comment]
Enso ecosystem is something that it built on top of Laravel. The technologies and techniques we're using determine our minimum requirements.

Sorry.
